name: flutter_localization
description: Flutter Localization is a package use for in-app localization with map data. More easier and faster to implement and inspired by the flutter_localizations itself.
version: 0.1.8
homepage: https://github.com/channdara/flutter_localization

# check package before publish: flutter pub publish --dry-run
# publish package: flutter pub publish

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mastertipsy.flutter_localization
        pluginClass: FlutterLocalizationPlugin
      ios:
        pluginClass: FlutterLocalizationPlugin
      linux:
        pluginClass: FlutterLocalizationPlugin
      macos:
        pluginClass: FlutterLocalizationPlugin
      windows:
        pluginClass: FlutterLocalizationPluginCApi